export const NEW_PRODUCT_INFO = 'NEW_PRODUCT_INFO';
export const NEW_PRODUCT_VARIANTS = 'NEW_PRODUCT_VARIANTS';
export const CREATE_NEW_PRODUCT = 'CREATE_NEW_PRODUCT';
export const CREATE_NEW_PRODUCT_ERROR = 'CREATE_NEW_PRODUCT_ERROR';
export const GET_ALL_PRODUCT_LIST = 'GET_ALL_PRODUCT_LIST';
export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING'
export const STORE_SHOP_ID = 'STORE_SHOP_ID'