export const nricConfigs = {
  NRIC: {
    state: [
      {
        value: 1,
      },
      {
        value: 2,
      },
      {
        value: 3,
      },
      {
        value: 4,
      },
      {
        value: 5,
      },
      {
        value: 6,
      },
      {
        value: 7,
      },
      {
        value: 8,
      },
      {
        value: 9,
      },
      {
        value: 10,
      },
      {
        value: 11,
      },
      {
        value: 12,
      },
      {
        value: 13,
      },
      {
        value: 14,
      },
    ],
    type: [
      {
        value: 'N',
      },
      {
        value: 'P',
      },
      {
        value: 'E',
      },
      {
        value: 'V',
      },
      {
        value: 'THI',
      },
      {
        value: 'THA',
      },
    ],
    township: {
      1: [
        { value: 'MA KA NA' },
        { value: 'SAH BA TA' },
        { value: 'WA MA NA' },
        { value: 'SAH DA NA' },
        { value: 'AH GA YA' },
        { value: 'TA NA NA' },
        { value: 'RA BHA YA' },
        { value: 'KHA PHA NA' },
        { value: 'SAH LA NA' },
        { value: 'KA PA TA' },
        { value: 'PA WA NA' },
        { value: 'MA NYA NA' },
        { value: 'HA PA NA' },
        { value: 'MA KA TA' },
        { value: 'KA MA NA' },
        { value: 'KA MA TA' },
        { value: 'BHA MA NA' },
        { value: 'RA KA NA' },
        { value: 'MA LA NA' },
        { value: 'MA MA NA' },
        { value: 'LA GA NA' },
        { value: 'DA PHA YA' },
        { value: 'MA SA NA' },
        { value: 'PA TA AH' },
        { value: 'MA KHA BA' },
        { value: 'NA MA NA' },
        { value: 'PA NA DA' },
        { value: 'KHA BA DA' },
        { value: 'SAH PA BA' },
      ],
      2: [
        { value: 'LA KA NA' },
        { value: 'DA MA SAH' },
        { value: 'PHA RA SAH' },
        { value: 'RA TA NA' },
        { value: 'BA LA KHA' },
        { value: 'PHA SAH NA' },
        { value: 'MA SA NA' },
        { value: 'RA THA NA' },
      ],
      3: [
        { value: 'BA AH NA' },
        { value: 'LA BA NA' },
        { value: 'PA KA NA' },
        { value: 'RA RA THA' },
        { value: 'THA TA KA' },
        { value: 'LA THA NA' },
        { value: 'BA GA LA' },
        { value: 'PHA PA NA' },
        { value: 'KA MA MA' },
        { value: 'KA KA RA' },
        { value: 'KA SAH KA' },
        { value: 'KA DA NA' },
        { value: 'BA THA SAH' },
        { value: 'MA WA TA' },
        { value: 'SA KA LA' },
        { value: 'WA LA MA' },
      ],
      4: [
        { value: 'HA KHA NA' },
        { value: 'HTA TA LA' },
        { value: 'PHA LA NA' },
        { value: 'RA KHA DA' },
        { value: 'TA TA NA' },
        { value: 'TA ZA NA' },
        { value: 'KA KHA NA' },
        { value: 'MA TA NA' },
        { value: 'MA TA PA' },
        { value: 'RA ZA NA' },
        { value: 'KA PA LA' },
        { value: 'PA LA WA' },
        { value: 'SAH MA NA' },
      ],
      5: [
        { value: 'SA KA NA' },
        { value: 'MA MA TA' },
        { value: 'MA MA NA' },
        { value: 'RA BA NA' },
        { value: 'WA LA NA' },
        { value: 'KHA AU NA' },
        { value: 'KA BA LA' },
        { value: 'KA LA NA' },
        { value: 'RA AU NA' },
        { value: 'DA PA YA' },
        { value: 'TA SAH NA' },
        { value: 'KA MA NA' },
        { value: 'MA RA NA' },
        { value: 'KHA AU TA' },
        { value: 'AH RA TA' },
        { value: 'BA TA LA' },
        { value: 'YA MA PA' },
        { value: 'PA LA NA' },
        { value: 'KA NA NA' },
        { value: 'SAH LA KA' },
        { value: 'KA THA NA' },
        { value: 'HTA KHA NA' },
        { value: 'AH TA NA' },
        { value: 'BHA MA NA' },
        { value: 'KA LA TA' },
        { value: 'PA LA BA' },
        { value: 'WA THA NA' },
        { value: 'KA LA HTA' },
        { value: 'KA LA WA' },
        { value: 'MA KA NA' },
        { value: 'TA MA NA' },
        { value: 'KHA PA NA' },
        { value: 'MA THA NA' },
        { value: 'MA LA NA' },
        { value: 'PHA PA NA' },
        { value: 'KHA TA NA' },
        { value: 'HA MA LA' },
        { value: 'LA RA NA' },
        { value: 'LA HA NA' },
        { value: 'NA YA NA' },
        { value: 'PA SAH NA' },
        { value: 'DA HA NA' },
        { value: 'MA PA LA' },
        { value: 'HTA PA KHA' },
        { value: 'SAH MA RA' },
      ],
      6: [
        { value: 'HTA WA NA' },
        { value: 'LA LA NA' },
        { value: 'THA RA KHA' },
        { value: 'RA PHA NA' },
        { value: 'MA TA NA' },
        { value: 'KA LA AH' },
        { value: 'MA AH RA' },
        { value: 'MA AH NA' },
        { value: 'KA SA NA' },
        { value: 'PA LA NA' },
        { value: 'TA THA RA' },
        { value: 'PA LA TA' },
        { value: 'KA THA NA' },
        { value: 'BA PA NA' },
        { value: 'KHA MA KA' },
        { value: 'PA KA MA' },
        { value: 'KA RA RA' },
      ],
      7: [
        { value: 'TA NGA NA' },
        { value: 'RA TA RA' },
        { value: 'HTA TA PA' },
        { value: 'AH TA NA' },
        { value: 'PHA MA NA' },
        { value: 'KA KA NA' },
        { value: 'PA KHA NA' },
        { value: 'KA TA KHA' },
        { value: 'RA KA NA' },
        { value: 'NYA LA PA' },
        { value: 'DA AU NA' },
        { value: 'WA MA NA' },
        { value: 'THA NA PA' },
        { value: 'KA WA NA' },
        { value: 'THA WA TA' },
        { value: 'LA PA TA' },
        { value: 'MA LA NA' },
        { value: 'MA NYA NA' },
        { value: 'AH HPA NA' },
        { value: 'KA PA KA' },
        { value: 'ZA KA NA' },
        { value: 'NA TA LA' },
        { value: 'PA MA NA' },
        { value: 'THA KA NA' },
        { value: 'RA TA NA' },
        { value: 'PA TA TA' },
        { value: 'PA TA NA' },
        { value: 'PA KHA TA' },
      ],
      8: [
        { value: 'MA KA NA' },
        { value: 'RA NA KHA' },
        { value: 'KHA MA NA' },
        { value: 'NA MA NA' },
        { value: 'MA THA NA' },
        { value: 'TA TA KA' },
        { value: 'MA BA NA' },
        { value: 'PA PHA NA' },
        { value: 'SA LA NA' },
        { value: 'SA TA RA' },
        { value: 'NGA PHA NA' },
        { value: 'THA RA NA' },
        { value: 'MA HTA NA' },
        { value: 'AH LA NA' },
        { value: 'KA MA NA' },
        { value: 'MA TA NA' },
        { value: 'SAH PA WA' },
        { value: 'MA LA NA' },
        { value: 'PA KHA KA' },
        { value: 'RA SA KA' },
        { value: 'MA MA NA' },
        { value: 'PA MA NA' },
        { value: 'SAH PHA NA' },
        { value: 'GA GA NA' },
        { value: 'SAH MA NA' },
        { value: 'HTA LA NA' },
        { value: 'KA HTA NA' },
      ],
      9: [
        { value: 'MA NA MA' },
        { value: 'AH MA ZA' },
        { value: 'MA RA MA' },
        { value: 'KHA AH ZA' },
        { value: 'MA NA TA' },
        { value: 'KHA MA SA' },
        { value: 'MA RA TA' },
        { value: 'MA HA MA' },
        { value: 'PA KA KHA' },
        { value: 'AH MA RA' },
        { value: 'PA THA KA' },
        { value: 'MA MA NA' },
        { value: 'PA AU LA' },
        { value: 'MA TA RA' },
        { value: 'SA KA NA' },
        { value: 'THA PA KA' },
        { value: 'MA KA NA' },
        { value: 'TA KA TA' },
        { value: 'KA SAH NA' },
        { value: 'SA KA TA' },
        { value: 'MA THA NA' },
        { value: 'TA TA AU' },
        { value: 'MA KHA NA' },
        { value: 'TA THA NA' },
        { value: 'KA PA TA' },
        { value: 'NA HTA KA' },
        { value: 'NYA AU NA' },
        { value: 'NGA ZA NA' },
        { value: 'NGA THA RA' },
        { value: 'MA HTA LA' },
        { value: 'THA SA NA' },
        { value: 'WA TA NA' },
        { value: 'RA MA THA' },
        { value: 'PA BA NA' },
        { value: 'AU TA THA' },
        { value: 'ZA YA THA' },
        { value: 'PA BHA THA' },
        { value: 'TA KA NA' },
        { value: 'DA KHA THA' },
        { value: 'ZA BHA THA' },
        { value: 'PA MA NA' },
        { value: 'LA WA NA' },
      ],
      10: [
        { value: 'MA LA MA' },
        { value: 'KA MA RA' },
        { value: 'KHA SAH NA' },
        { value: 'THA PHA RA' },
        { value: 'MA DA NA' },
        { value: 'RA MA NA' },
        { value: 'LA MA NA' },
        { value: 'KHA ZA NA' },
        { value: 'THA HTA NA' },
        { value: 'PA MA NA' },
        { value: 'KA HTA NA' },
        { value: 'BA LA NA' },
      ],
      11: [
        { value: 'SA TA NA' },
        { value: 'RA THA TA' },
        { value: 'PA NAG KA' },
        { value: 'PA TA NA' },
        { value: 'MA AU NA' },
        { value: 'MA PA NA' },
        { value: 'KA TA NA' },
        { value: 'MA PA TA' },
        { value: 'MA TA NA' },
        { value: 'BA THA TA' },
        { value: 'TA PA WA' },
        { value: 'KA PHA NA' },
        { value: 'RA BHA NA' },
        { value: 'MA AH NA' },
        { value: 'AH MA NA' },
        { value: 'THA TA NA' },
        { value: 'TA KA NA' },
        { value: 'MA AH TA' },
        { value: 'GA MA NA' },
        { value: 'KA TA LA' },
      ],
      12: [
        { value: 'THA HGA KA' },
        { value: 'RA KA NA' },
        { value: 'AU KA TA' },
        { value: 'AU KA MA' },
        { value: 'THA KA TA' },
        { value: 'DA PA NA' },
        { value: 'TA MA NA' },
        { value: 'PA ZA TA' },
        { value: 'BHA TA HTA' },
        { value: 'MA GA TA' },
        { value: 'DA GA MA' },
        { value: 'DA GA RA' },
        { value: 'DA GA TA' },
        { value: 'DA GA SAH' },
        { value: 'KA TA TA' },
        { value: 'PA BA TA' },
        { value: 'LA MA TA' },
        { value: 'LA THA NA' },
        { value: 'AH LA NA' },
        { value: 'KA MA TA' },
        { value: 'SA KHA NA' },
        { value: 'LA MA NA' },
        { value: 'KA MA RA' },
        { value: 'MA RA KA' },
        { value: 'DA GA NA' },
        { value: 'BHA HA NA' },
        { value: 'SAH KA NA' },
        { value: 'THA LA NA' },
        { value: 'KA TA NA' },
        { value: 'TA TA TA' },
        { value: 'THA KHA NA' },
        { value: 'KHA RA NA' },
        { value: 'TA TA NA' },
        { value: 'KA MA NA' },
        { value: 'KA KHA KA' },
        { value: 'DA LA NA' },
        { value: 'SAH KA KHA' },
        { value: 'KA KA KA' },
        { value: 'AH SA NA' },
        { value: 'MA GA DA' },
        { value: 'MA BA NA' },
        { value: 'LA KA NA' },
        { value: 'TA KA NA' },
        { value: 'HTA TA PA' },
        { value: 'RA PA THA' },
        { value: 'LA THA YA' },
      ],
      13: [
        { value: 'TA KA NA' },
        { value: 'HA PA NA' },
        { value: 'NYA RA NA' },
        { value: 'SAH SAH NA' },
        { value: 'KA LA NA' },
        { value: 'PA TA YA' },
        { value: 'RA NGA NA' },
        { value: 'RA SA NA' },
        { value: 'PA LA NA' },
        { value: 'PHA KHA NA' },
        { value: 'KA TA LA' },
        { value: 'NA TA RA' },
        { value: 'AH TA NA' },
        { value: 'LA LA NA' },
        { value: 'LA KHA NA' },
        { value: 'NA SA NA' },
        { value: 'KA HA NA' },
        { value: 'KA THA NA' },
        { value: 'MA KA NA' },
        { value: 'MA RA NA' },
        { value: 'PA LA TA' },
        { value: 'MA NA TA' },
        { value: 'KHA LA NA' },
        { value: 'KA LA DA' },
        { value: 'MA SA NA' },
        { value: 'LA KHA TA' },
        { value: 'MA NA NA' },
        { value: 'MA MA NA' },
        { value: 'MA PA NA' },
        { value: 'HA MA NA' },
        { value: 'KA TA TA' },
        { value: 'LA RA NA' },
        { value: 'THA NA NA' },
        { value: 'TA YA NA' },
        { value: 'MA RA TA' },
        { value: 'KA LA TA' },
        { value: 'PA YA NA' },
        { value: 'NA PHA NA' },
        { value: 'MA PHA TA' },
        { value: 'PA SAH NA' },
        { value: 'MA KA HTA' },
        { value: 'MA SAH TA' },
        { value: 'NA KHA NA' },
        { value: 'KA KHA NA' },
        { value: 'TA MA NYA' },
        { value: 'MA HA RA' },
        { value: 'MA KA TA' },
        { value: 'PA SAH TA' },
        { value: 'KA MA NA' },
        { value: 'THA PA NA' },
        { value: 'NA KHA TA' },
        { value: 'NA MA TA' },
        { value: 'NA SAH NA' },
        { value: 'MA TA TA' },
        { value: 'MA NGA NA' },
        { value: 'MA LA TA' },
        { value: 'MA MA TA' },
        { value: 'MA BA NA' },
        { value: 'HA PA TA' },
        { value: 'PA WA NA' },
        { value: 'MA MA HTA' },
        { value: 'NA TA NA' },
        { value: 'PA LA HTA' },
        { value: 'LA KA NA' },
        { value: 'KA KA NA' },
        { value: 'KHA RA HA' },
        { value: 'MA HTA TA' },
        { value: 'KA TA NA' },
        { value: 'MA LA NA' },
        { value: 'MA YA NA' },
        { value: 'MA PA HTA' },
        { value: 'MA KHA NA' },
        { value: 'MA PA TA' },
        { value: 'TA TA NA' },
        { value: 'MA SAH NA' },
        { value: 'MA KHA TA' },
        { value: 'MA TA NA' },
        { value: 'PA PA KA' },
        { value: 'MA HTA NA' },
        { value: 'MA PHA NA' },
        { value: 'MA YA TA' },
        { value: 'MA YA HTA' },
        { value: 'TA KHA LA' },
        { value: 'TA LA NA' },
        { value: 'KA LA HTA' },
      ],
      14: [
        { value: 'PA THA NA' },
        { value: 'RA THA YA' },
        { value: 'NGA SAH NA' },
        { value: 'PA THA RA' },
        { value: 'KA KA HTA' },
        { value: 'NGA PA TA' },
        { value: 'HA KA KA' },
        { value: 'NGA RA KA' },
        { value: 'THA PA NA' },
        { value: 'KA KA NA' },
        { value: 'RA KA NA' },
        { value: 'NGA THA KHA' },
        { value: 'KA PA NA' },
        { value: 'HA THA TA' },
        { value: 'ZA LA NA' },
        { value: 'LA MA NA' },
        { value: 'AH GA PA' },
        { value: 'MA AH NA' },
        { value: 'KA KHA NA' },
        { value: 'MA AH PA' },
        { value: 'PA TA NA' },
        { value: 'NYA TA NA' },
        { value: 'DHA NA PHA' },
        { value: 'PHA PA NA' },
        { value: 'AH MA TA' },
        { value: 'BA KA LA' },
        { value: 'KA LA NA' },
        { value: 'DA DA RA' },
        { value: 'LA PA TA' },
        { value: 'PA SA LA' },
        { value: 'MA MA KA' },
        { value: 'MA MA NA' },
        { value: 'AH MA NA' },
        { value: 'WA KHA MA' },
      ],
    },
  },
};